# Random shit

In [3]:
import numpy as np
import pandas as pd
import os

In [16]:
arr = np.load('user/data/ref_data/target_hist_1D.npy')

grid_min = [-0.016]  # Min values for the 2D grid
grid_max = [0.016]  # Max values for the 2D grid
num_points = [99]  # Number of points in the grid (X and Y dimensions)

x_grid = np.linspace(grid_min[0], grid_max[0], num_points[0]) 
arr = np.stack((x_grid, arr), axis=1)
np.save('user/data/ref_data/target.npy', arr)

In [7]:
start_iter = 2
prev_it = start_iter - 1
fn = f"output/pso_state_it{prev_it}.npz"
if os.path.isfile(fn):
    data = np.load(fn)
    print(data)
    print(data["X"])
    print(data["V"])
    print(data["P"])
    #data["Pf"]
    #data["g"]
    #float(data["gf"])

NpzFile 'output/pso_state_it1.npz' with keys: X, V, P, Pf, g...
[[0.86161384 0.36432502 0.65229723 1.76532516]
 [0.78263645 0.25569479 0.58990941 1.78367584]]
[[ 0.          0.          0.          0.        ]
 [ 0.15630676 -0.16       -0.4         0.4       ]]
[[0.86161384 0.36432502 0.65229723 1.76532516]
 [0.62632969 0.41569479 0.98990941 1.38367584]]
